meta_product_name: "Bibliotech"
meta_title: "Bibliotech - Next-Gen Reading Lists"
meta_description: "Find the books that inspired you role models! Using AI, Bibliotech created personalised reading lists that you can save to your own library."
meta_image: "meta_home.png" # should exist in `app/assets/images/`